version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
      TZ: Asia/Tokyo
    ports:
      - 3377:3306

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rails_app
    container_name: rails_app
    environment:
      EDITOR: vim
      RUBYOPT: '-W:no-deprecated'
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    command: /bin/sh -c "bundle && rm -f /app/tmp/pids/server.pid && bundle exec foreman start -f Procfile"
    ports:
      - 3070:3000
      - 8888:8888
      - 3035:3035
    volumes:
      - .:/app:cached
      - app-data-store:/bundle
    depends_on: 
      - db

volumes:
  app-data-store:
    driver: local